R/def_environments.R, man/def_environments.Rd
Hi @ChristopherDavidDean, very minor changes suggested! Let me know what you think.
=> REVIEW: def_environments()

R/def_lithology_att.R, R/def_timescales.R
Hi @LewisAJones, tiny changes here - main one being reordering the return description to match the order of columns. Cheers!
=> REVIEW: def_timescales()

R/def_structures.R, man/def_structures.Rd
Hi @willgearty, some small suggested changes, looking good though!
=> REVIEW: def_structures()

R/def_columns.R, man/def_columns.Rd
Hi @willgearty, a few changes here, mostly stemming from the returned data.frame containing additional columns not mentioned in the Macrostrat API. Otherwise all fine and works a treat! Cheers!
=> REVIEW: def_columns()

R/get_map_outcrop.R, man/get_map_outcrop.Rd
Hi @willgearty - Surprise, minor suggestions! Looks and works great.
=> REVIEW: get_map_outcrop()

R/def_plates.R, man/def_plates.Rd
Basically no changes here, bar the title. Thanks!
=> REVIEW: def_plates()

R/def_measurements.R, man/def_measurements.Rd
Very small changes here, just formatting and language. Cheers Will!
=> REVIEW: def_measurements()

R/def_references.R, man/def_references.Rd
Hi @willgearty, I tweaked some of the wording but otherwise looks great.
=> REVIEW: def_references()

R/get_columns.R, man/get_columns.Rd
This all looks great @willgearty, minor changes for consistency. Let me know your thoughts!
=> REVIEW: get_columns()

R/def_intervals.R, man/def_intervals.Rd
Hi @LewisAJones! I added an extra column for the return of the function and updated some other minor documentation stuff. Otherwise, it looks good!
=> REVIEW: def_intervals()

R/get_fossils.R, man/get_fossils.Rd
Hi @ChristopherDavidDean! Looks good, a few suggested changes, let me know what you think!
=> REVIEW: get_fossils()

R/def_grain_sizes.R, man/def_grain_sizes.Rd
Very minor changes to align the style with the rest of the package @LewisAJones. Let me know what you think!
=> REVIEW: def_grain_sizes()

R/get_age_model.R, man/get_age_model.Rd, tests/testthat/test-get_age_model.R
Hi @bethany-j-allen, not much to contribute here from my side! I've made a few suggested changes - let me know what you think!
=> REVIEW: get_age_model()

R/get_eodp.R, man/get_eodp.Rd, tests/testthat/test-get_eodp.R
Hi @bethany-j-allen, just some changes to align the documentation with the rest of the package. Otherwise it looks great, thanks!
=> REVIEW: get_eodp()

R/def_econs.R, man/def_econs.Rd
Just some minor style changes @bethany-j-allen, otherwise looks great!
=> REVIEW: def_econs()

R/get_measurements.R, man/get_measurements.Rd
HI @bethany-j-allen, all looks good and all the examples work a treat. Let me know your thoughts!
=> REVIEW: get_measurements()

R/def_minerals.R, man/def_minerals.Rd
Hi @LewisAJones, I reordered the return columns and added a link to Mindat, where the URLs lead for a more extensive definition. But otherwise just a few typos, looks good!
=> REVIEW: def_minerals()

R/def_lithologies.R
Hi @willgearty, looks good! I tweaked some of the wording but otherwise looks great.
Question: for `color`, do we want to state that this is the 'hex' or 'hexadecimal' code?
=> REVIEW: def_lithologies()

R/get_stats.R, man/get_stats.Rd
Hi @willgearty, this looks fine - the only big change was that I annotated the example and assigned it to a variable. I wonder whether we should add a sentence somewhere to say that the function has no arguments?
=> REVIEW: get_stats()

R/def_strat_name_concepts.R, man/def_strat_name_concepts.Rd
Just some very minor changes to update the style of the function @ChristopherDavidDean. Let me know what you think!
=> REVIEW: def_strat_name_concepts()

R/def_strat_names.R, tests/testthat/test-def_strat_names.R
Hi @ChristopherDavidDean: I made a few changes here, namely adding indents, tweaking some of the text, and adding error messages when using the `rule` argument. Let me know if there's anything you disagree with.
=> REVIEW: def_strat_names()
